[Meter1P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter1Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter1A]
Meter=String
MeasureName=MyMeasure

[Meter1B]
Meter=String
MeasureName=MyMeasure

[Meter1C]
Meter=String
MeasureName=MyMeasure

[Meter1D]
Meter=String
MeasureName=MyMeasure

[Meter2P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter2Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter2A]
Meter=String
MeasureName=MyMeasure

[Meter2B]
Meter=String
MeasureName=MyMeasure

[Meter2C]
Meter=String
MeasureName=MyMeasure

[Meter2D]
Meter=String
MeasureName=MyMeasure

[Meter3P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter3Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter3A]
Meter=String
MeasureName=MyMeasure

[Meter3B]
Meter=String
MeasureName=MyMeasure

[Meter3C]
Meter=String
MeasureName=MyMeasure

[Meter3D]
Meter=String
MeasureName=MyMeasure

[Meter4P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter4Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter4A]
Meter=String
MeasureName=MyMeasure

[Meter4B]
Meter=String
MeasureName=MyMeasure

[Meter4C]
Meter=String
MeasureName=MyMeasure

[Meter4D]
Meter=String
MeasureName=MyMeasure

[Meter5P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter5Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter5A]
Meter=String
MeasureName=MyMeasure

[Meter5B]
Meter=String
MeasureName=MyMeasure

[Meter5C]
Meter=String
MeasureName=MyMeasure

[Meter5D]
Meter=String
MeasureName=MyMeasure

[Meter6P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter6Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter6A]
Meter=String
MeasureName=MyMeasure

[Meter6B]
Meter=String
MeasureName=MyMeasure

[Meter6C]
Meter=String
MeasureName=MyMeasure

[Meter6D]
Meter=String
MeasureName=MyMeasure

[Meter7P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter7Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter7A]
Meter=String
MeasureName=MyMeasure

[Meter7B]
Meter=String
MeasureName=MyMeasure

[Meter7C]
Meter=String
MeasureName=MyMeasure

[Meter7D]
Meter=String
MeasureName=MyMeasure

[Meter8P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter8Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter8A]
Meter=String
MeasureName=MyMeasure

[Meter8B]
Meter=String
MeasureName=MyMeasure

[Meter8C]
Meter=String
MeasureName=MyMeasure

[Meter8D]
Meter=String
MeasureName=MyMeasure

[Meter9P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter9Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter9A]
Meter=String
MeasureName=MyMeasure

[Meter9B]
Meter=String
MeasureName=MyMeasure

[Meter9C]
Meter=String
MeasureName=MyMeasure

[Meter9D]
Meter=String
MeasureName=MyMeasure

[Meter10P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter10Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter10A]
Meter=String
MeasureName=MyMeasure

[Meter10B]
Meter=String
MeasureName=MyMeasure

[Meter10C]
Meter=String
MeasureName=MyMeasure

[Meter10D]
Meter=String
MeasureName=MyMeasure

[Meter11P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter11Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter11A]
Meter=String
MeasureName=MyMeasure

[Meter11B]
Meter=String
MeasureName=MyMeasure

[Meter11C]
Meter=String
MeasureName=MyMeasure

[Meter11D]
Meter=String
MeasureName=MyMeasure

[Meter12P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter12Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter12A]
Meter=String
MeasureName=MyMeasure

[Meter12B]
Meter=String
MeasureName=MyMeasure

[Meter12C]
Meter=String
MeasureName=MyMeasure

[Meter12D]
Meter=String
MeasureName=MyMeasure

[Meter13P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter13Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter13A]
Meter=String
MeasureName=MyMeasure

[Meter13B]
Meter=String
MeasureName=MyMeasure

[Meter13C]
Meter=String
MeasureName=MyMeasure

[Meter13D]
Meter=String
MeasureName=MyMeasure

[Meter14P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter14Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter14A]
Meter=String
MeasureName=MyMeasure

[Meter14B]
Meter=String
MeasureName=MyMeasure

[Meter14C]
Meter=String
MeasureName=MyMeasure

[Meter14D]
Meter=String
MeasureName=MyMeasure

[Meter15P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter15Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter15A]
Meter=String
MeasureName=MyMeasure

[Meter15B]
Meter=String
MeasureName=MyMeasure

[Meter15C]
Meter=String
MeasureName=MyMeasure

[Meter15D]
Meter=String
MeasureName=MyMeasure

[Meter16P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter16Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter16A]
Meter=String
MeasureName=MyMeasure

[Meter16B]
Meter=String
MeasureName=MyMeasure

[Meter16C]
Meter=String
MeasureName=MyMeasure

[Meter16D]
Meter=String
MeasureName=MyMeasure

[Meter17P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter17Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter17A]
Meter=String
MeasureName=MyMeasure

[Meter17B]
Meter=String
MeasureName=MyMeasure

[Meter17C]
Meter=String
MeasureName=MyMeasure

[Meter17D]
Meter=String
MeasureName=MyMeasure

[Meter18P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter18Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter18A]
Meter=String
MeasureName=MyMeasure

[Meter18B]
Meter=String
MeasureName=MyMeasure

[Meter18C]
Meter=String
MeasureName=MyMeasure

[Meter18D]
Meter=String
MeasureName=MyMeasure

[Meter19P]
Meter=Shape
MyGradient=180 | #Background# ; 0.0  | #Background# ; 0.6 | #Background2# ; 1.0
Shape=Rectangle 0,0,#RectWidth#,#RectHeight#,#RectRadius# | Fill LinearGradient MyGradient | Stroke Color 0,0,0,1

[Meter19Q]
Meter=Shape
Shape=Rectangle 0,0,5,#RectHeight# | Fill Color #Accent# | Stroke Color 0,0,0,1

[Meter19A]
Meter=String
MeasureName=MyMeasure

[Meter19B]
Meter=String
MeasureName=MyMeasure

[Meter19C]
Meter=String
MeasureName=MyMeasure

[Meter19D]
Meter=String
MeasureName=MyMeasure

